module_register = "Sign-Up"

########
# Form #
########
mt_register_form = "Register"
md_register_form = "Signup on this PyGDO Website."

#########
# Guest #
#########
mt_register_guest = "Continue as Guest"
md_register_guest = "Use this PyGDO Website as a guest user. You cannot recover if you loose your password."
link_back_to = 'back'
msg_guest_created = "You are now using the site as %s."
msg_guest_created_back = "You are now using the site as %s. Go %s from where you came."
